### ISSUE TITLE
objects_to_consider_query_storage_file or cache_folder_filepath ?

### ISSUE THREAD

**Issue by Marc-marc-marc** [matkoniecz/osm_bot_abstraction_layer#5]
[Usage example : Bot edit](https://github.com/matkoniecz/osm_bot_abstraction_layer#bot-edit) use `objects_to_consider_query_storage_file`
running with it produce the error
`TypeError: run_simple_retagging_task() got an unexpected keyword argument 'objects_to_consider_query_storage_file'`

removing it and using `cache_folder_filepath` work fine

**Comment by matkoniecz** [comment]
thanks for a report!
