### ISSUE TITLE
automatic=yes/no changeset tag

### ISSUE THREAD

**Issue by Marc-marc-marc** [matkoniecz/osm_bot_abstraction_layer#6]
if I read the code correctly
- changeset tag automatic is set by osm_bot_abstraction_layer.py L25 from automatic_status
- automatic_status is set in generic_bot_retagging.py L24 from is_in_manual_mode

so
- if you are in "is_in_manual_mode" True, it's not an mechanical/bot edit anymore but changeset tag bot=yes is still set (and automatic=no) (bot=no seems better to express that despite using a created_by that is "bot like", it's a reviewed edit
- if you are in "is_in_manual_mode" False, automatic=yes is set, undocumented duplicate of mechanical/bot=yes

what's the usecase of it ?

**Comment by matkoniecz** [comment]
I guess that what is mentioned here makes sense.

I would accept PR changing this, there is also decent chance that I will modify this.

**Comment by matkoniecz** [comment]
https://wiki.openstreetmap.org/wiki/ChangesetKey:mechanical is up

https://wiki.openstreetmap.org/wiki/Automated_Edits_code_of_conduct describes it

set in https://github.com/matkoniecz/osm_bot_abstraction_layer/blob/master/osm_bot_abstraction_layer/osm_bot_abstraction_layer.py#L25

**Comment by matkoniecz** [comment]
> if you are in "is_in_manual_mode" True, it's not an mechanical/bot edit anymore but changeset tag bot=yes is still set 

not anymore from looking at code
